version: 1.0.{build}
image: Visual Studio 2017
configuration: DeBug
platform: x64
clone_folder: C:\Users\DELL\Desktop\project\alg
build:
  project: fastsortList\fastsortList.sln
  publish_wap: true
  publish_azure_webjob: true
  publish_azure: true
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  include_nuget_references: true
  publish_aspnet_core: true
  publish_core_console: true
  parallel: true
  verbosity: minimal
after_build:
- cmd: echo 成功
before_test:
- cmd: >-
    echo 测试开始

    vstest.console /logger:Appveyor fastsortList\x64\Debug\*.Test.dll
after_test:
- cmd: echo 测试结束
artifacts:
- path: fastsortList\x64\Debug\*dll
  name: myalg
deploy:
- provider: GitHub
  auth_token:
    secure: RrmgG2pXCEIFgz1dsD2eKnG1Z/8nTTKeFoIZ8aXapl9FWrpiL4mPvshFcnj03G9h
notifications:
- provider: Email
  to:
  - 2993424163@qq.com
  subject: 构建项目
  message: 成功
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
- provider: Email
  to:
  - 2993424163@qq.com
  subject: 构建项目失败
  message: 失败
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
on_success:
- cmd: echo 成功建立
on_failure:
- cmd: >-
    git config --global user.email "2993424163@qq.com"

    git config --global user.name "xzs-xx"

    git reset --hard HEAD^

    git pull origin zsxie

    git add .

    git commit -m "提交失败"

    git push origin zsxie